language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
- gem install compass
before_script:
- npm install --quiet -g grunt-cli karma bower
- npm install
- bower install
script: grunt
deploy:
  provider: s3
  access_key_id: AKIAICNC6OORFFQWNT6A
  secret_access_key:
    secure: LSHHycCrT/lh4/1oFGY8ZOV8QRIoyj0ejRGepRmKhcmIyh3//PvdBeTvahNcfYpqeaXj5nbdlmBEXpMjKbCts5U2fEIaMp4+J/htDfpvM45fgeCs5qTkrBrm7XlAbUdB2RQLppZZ5UF+vQOjjyABhf3Dna6QWJOFbXDSDxP49ao=
  bucket: avalancheca-website
  local-dir: "build"
  skip_cleanup: true
  region: us-west-2
  on:
    repo: avalanchedotca/AvalancheCanada
