language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
- gem install compass
before_script:
- npm install --quiet -g grunt-cli karma bower
- npm install
- bower install
script: grunt
deploy:
  provider: s3
  access_key_id: AKIAJGY4NU4JHXJWJDQQ
  secret_access_key:
    secure: E3jn5/PNeBoQm2DXsJCXBZ4LIR5IJPbSbQF1wKpq9aTSHrxtipR/LK2nf9Cy0H4Zy4XzcUbGmK1tDXNsNq6itekOcwhO3eeldw3bIWt9OB7KfdYbEtUDj3gPNuDhnAZ9skNmL/j15h8mSdYi9K3amojkK5ZdvW/2lMJnQyRB2c8=
  bucket: avalanche.ca
  local-dir: "build"
  skip_cleanup: true
  on:
    repo: avalanchedotca/AvalancheCanada
