language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- gem install sass
- bower install
deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id: AKIAICNC6OORFFQWNT6A
  secret_access_key: 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
  app: avalanche-canada
  env: avalanche-canada-env
  region: us-west
  on:
    repo: avalanchedotca/AvalancheCanada
